version: '2'
services:
  mysql:
    build: ./mysql
    container_name: "${MYSQL_NAME}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  php:
    build: ./php
    container_name: "${PHP_NAME}"
    ports:
      - "${PHP_PORT}:80"
      - "${PHP_SSL_PORT}:443"
    volumes:
      - ./application:/application
    depends_on:
      - mysql
    links:
      - mysql
    privileged: true
    command: /sbin/init

  adminer:
    container_name: "${ADMINER_NAME}"
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  db:
  sessions:

